### ISSUE TITLE
Checklist for Week 12

### ISSUE THREAD

**Issue by kazuhiroinaba** [CS2103AUG2016-W10-C1/main#129]
## Product
- [x] Implement all the features you intend to release.
- Otherwise, build tests, fix bugs and clean code (if there is time). 

## Demo
- [x] Populate seed (~ 50 entries)
- [x] Release the version tagged V0.5rc.

## Tutorial Activities
- [x] T11A2: Pick task (a) or (b). Ensure at least one member picks each task and no more than one member picks the same concept/rule. Preferably, try to pick concepts/rules that you think are not applicable to the project.
> (a) Relate three key concepts of Scrum to your project.
> e.g. product backlog, product owner, sprints, sprint backlog, daily scrum, user stories, scrumboard, story points, burndown charts, team velocity, scrum master, etc.
> 
> (b) Relate three XP rules to your project.
> 
> "Relate" here means: Is it applicable in your project? If not, why not? Are you using something similar or an alternative in your project? etc.

- [x] T11A3: Find platforms, frameworks, and libraries you are using in the project.
What are other alternative/additional platforms/frameworks/libraries you could have used in the project? 
- [x] T11A4: Use Activity Diagrams and/or Object Oriented Domain Models to explain the problem domain or the design of your project.
