### ISSUE TITLE
Checklist for week 11

### ISSUE THREAD

**Issue by kazuhiroinaba** [CS2103AUG2016-W10-C1/main#51]
## Demo
- [x] Create seed.
- [x] **Rigorous Dogfooding** (refactor or fix bugs while manually using the app), and don't break working tests.
- [x] Release the version tagged V0.4.
- [x] Do manual tests using the jar file, not the IDE.
- [x] Split features to cover.
## Product
- [x] Mark your code with special tag @@author.
- [x] Use the collate tool to extract individual code and look through the generated .md files to ensure all your code has been extracted correctly.
- [x] Push the *.md files created to a folder called /collated in your repository.
- [x] Push the code (including the collated folder and files created above) and tag as V0.4.

[For detailed intructions on collate](http://www.comp.nus.edu.sg/~cs2103/AY1617S1/contents/handbook.html#handbook-project-v04)
- [x] Implement all must have features. Refer to #28 
## Documentation
- [x] Update the AboutUs.md page to reflect the product. Use appropriate hyperlinks to substantiate your claimed contribution. [Sample AboutUs.md](https://github.com/nus-cs2103/website/blob/master/contents/AboutUs.md)
- [x] Include User Guide and Documentation Guide in the version tagged V0.4.
### Individual Learning Activities
- Get a team member to review at least 1 of your PR. Review at least 1 PR of a team member.
- Refer to [ Apply Design Patterns [LO-DesignPatterns]](https://github.com/nus-cs2103-AY1617S1/addressbook-level4/blob/master/docs/LearningOutcomes.md#apply-design-patterns-lo-designpatterns) and the relevant lecture handout. Find which design patterns are used in the AddressBook design. Are they still in your design too?
  Find if those patterns can be applied in other places of your design. 
- Refer to the learning outcomes [Write Integration Tests [LO-IntegrationTests]](https://github.com/nus-cs2103-AY1617S1/addressbook-level4/blob/master/docs/LearningOutcomes.md#write-integration-tests-lo-integrationtests) and [Perform System Testing [LO-SystemTesting]](https://github.com/nus-cs2103-AY1617S1/addressbook-level4/blob/master/docs/LearningOutcomes.md#perform-system-testing-lo-systemtesting) to find examples of unit/integration/system tests in AddressBook. Find tests in your projects that are unit tests, integration tests, unit + integration tests and system tests.
### Low Priority
- Update User Guide and Developer Guide to match the product.
- Resolve and enhance tests.

**Comment by alexfjw** [comment]
In terms of code, we have to achieve the following.

Must do features:
- [x] Storageloc (YM)
- [x] Allow user to add and list 3 item types (Inaba)
- [x] Allow user to edit all 3 item types ( ? )
- [x] Track deadlines (Inaba)
- [x] Undo (JY)

Support for tags is not essential.
We should finish these first, then update Docs.
We should also test these properly to ensure that there's no hidden bug. Get more tests working at the same time. (We're graded for test coverage)
- [x] Verify that all Must-Have's are completed. Refer to #28

Conduct dog fooding.
Decide what other new, nice to have features to add in.
-> This includes the new Issues created by JY, and the one on multiple schedules I was working on.

// Edit 

-> Do someday
Make prettytime work for deadline 
Make frequency repeat the deadline of the task & set task to incomplete
Would be a useless field otherwise
